FROM 763104351884.dkr.ecr.us-west-2.amazonaws.com/pytorch-training:1.12.0-gpu-py38-cu113-ubuntu20.04-sagemaker
COPY ./train_dis.py /
WORKDIR /
RUN apt-get update && apt-get install -y libsndfile1
RUN pip install wandb
ENV SAGEMAKER_SUBMIT_DIRECTORY /
ENV SAGEMAKER_PROGRAM /train_dis.py
